=== itsmemarioss/alura/javaee/xml/src/main/resources/venda.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:element name="venda">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="formaDePagamento" type="xsd:string" />
				<xsd:element name="produtos">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element ref="produto" maxOccurs="unbounded"></xsd:element>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
			</xsd:sequence>
			<xsd:attribute name="moeda" type="xsd:string"></xsd:attribute>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="produto">
		<xsd:complexType>
			<xsd:all>
				<xsd:element name="id" type="xsd:long"></xsd:element>
				<xsd:element name="nome" type="xsd:string"></xsd:element>
				<xsd:element name="valor" type="xsd:double"></xsd:element>
			</xsd:all>
		</xsd:complexType>
	</xsd:element>

</xsd:schema>

=== itsmemarioss/alura/javaee/xml/src/main/resources/venda.xml
<venda moeda="real" xsi:noNamespaceSchemaLocation="venda.xsd"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	
	<formaDePagamento>CREDITO</formaDePagamento>
	<produtos>
		<produto>
			<id>123</id>
			<nome>livro</nome>
			<valor>23.8</valor>
		</produto>
		<produto>
			<id>342</id>
			<nome>caderno</nome>
			<valor>5.00</valor>
		</produto>
	</produtos>
</venda>
